robot:
  name: "ABB_ULSA"
  ip: "host.docker.internal"
  port: 5000
  timeout: 30000

users:
  - username: "uwunyaguy"
    password: "uwunyanichan"
  - username: "chicojava"
    password: "tenesqueprobarnixos"
  - username: "ariari"
    password: "iraira"
  - username: "donbigo"
    password: "perosiesdonbigo"
  - username: "skibidi"
    password: "toilet"
